a = "b"
c = 10
e = 123.456

[y]
x = "y"
z = [1,2,3]

[A]
    x = "y"
    [A.B.C]
        m = "n"
    [A.B]
        D = ["x", "y", "z"]
        # [C]
        # [A.B.C]

# str = "str-toml"
# int = 101
# http_port = 65000
# [sub]
# float = 999.111

# {
#     "a": "b",
#     "c": 10,
#     "e": 123.456,
#     "y": {
#         "x": "y",
#         "z": ["1", "2", "3"]
#     },
#     "A": {
#         "x": "y",
#         "B": {
#             "C": {
#                 "m": "n"
#             },
#             "D": ["x", "y", "z"]
#         }
#     }
# }